---
- name: import the elasticsearch apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true
- name: add repository to sources list
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com groovy main
  become: true
- name: install terraform
  apt:
    name: terraform
    state: latest
  become: true
