---
- name: Update apt
  apt:
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
  become: true

- name: Install snap packages
  snap:
    name: "{{ snap_packages }}"
  become: true

- name: Link fd from fd-find
  file:
    src: /usr/bin/fdfind
    dest: ~/.local/bin/fd
    state: link

- name: Download diff-so-fancy
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: ~/.local/bin/diff-so-fancy
    mode: '0775'
