---
- name: Install zsh with brew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - zsh-completions

- name: Link zshrc
  file:
    src: ~/.dotfiles/zsh/zshrc
    dest: ~/.zshrc
    state: link
    mode: 0644
