---
- name: Make sure config folder existed
  file:
    path: ~/.config/alacritty
    state: directory
    mode: 0700

- name: Link alacritty
  file:
    src: ~/.dotfiles/alacritty/alacritty.mac.yml
    dest: ~/.config/alacritty/alacritty.yml
    state: link
    mode: 0644
