---
- name: Make sure config folder existed
  file:
    path: ~/.config/alacritty
    state: directory
    mode: 0700

- name: Link alacritty
  file:
    src: ~/.dotfiles/alacritty/alacritty.mac.toml
    dest: ~/.config/alacritty/alacritty.toml
    state: link
    mode: 0644
