---
- name: Install CLI tools with Homebrew
  homebrew:
    name:
      - gnu-which
      - gawk
      - bash
      - less
      - make
      - tig
      - htop
      - watch
      - jq
      - bat
      - exa
    state: present

