---
- name: Make sure apt packages are installed
  apt:
    name: "{{ apt_apps }}"
    state: latest
    update_cache: true
  become: true

- name: Make sure snap packages are installed
  snap:
    name: "{{ snap_apps }}"
  become: true
