---
- name: Install php with apt
  apt:
    name:
      - php-fpm
      - php-mbstring
      - php-xml
      - php-zip
      - php-mysql
    state: present
  become: true

- name: Download composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0755

- name: Run composer installer.
  command:
    cmd: >
      php /tmp/composer-setup.php
      --install-dir=/usr/local/bin
      --filename=composer
  become: true
