---
- name: Load OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"
- name: Install python library
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python_pip_excutable }}"
  with_items: "{{ python_packages }}"
