# If you come from bash you might have to change your $PATH.
[[ ":$PATH:" =~ ":/usr/local/bin:" ]] || PATH="/usr/local/bin:$PATH"
[[ ":$PATH:" =~ ":$HOME/bin:" ]] || PATH="$HOME/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# my option: bira, darkblood, gnzh, funky
# custom Themes: bira-red
ZSH_THEME="twoline"
if [[ 'Darwin' == $(uname -s) ]]; then
    ZSH_THEME="pi"
fi

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line if you want to change the command execution time
HIST_STAMPS="yyyy-mm-dd"

# Use another custom folder than $ZSH/custom
ZSH_CUSTOM=$HOME/.dotfiles/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    docker
    git
    go
    #nvm
    thefuck
    yarn
    vagrant
    composer
)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# colors
[[ "$TERM" == "xterm"  ]] && export TERM=xterm-256color

# print system info
#command -v neofetch &> /dev/null && neofetch

#
# fix wrong language setting
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
